package br.com.plataformalancamento.enumeration;

public enum TipoCanalPagamentoEnumeration {
	INTERNET_BANCKING, DEPOSITO_BANCARIO_CAIXA_ELETRONICO, DEPOSITO_BANCARIO_CAIXA_AGENCIA, MERCADO_PAGO, PAGAMENTO_CAIXA, DESCONTO_AUTOMATICO_CONTA_CORRENTE;
}
